name: Backend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Make db_controller.sh executable
        run: chmod +x db_controller.sh

      - name: Running test
        run: |
          ./db_controller.sh test
