name: Frontend Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  frontend-lint:
    - name: Install dependencies and lint
      run: |
        cd frontend
        npm install
        npm run lint